### PR TITLE
More cleanup for Tanya

### PR DESCRIPTION
**Pull request by DomHeinzeller**
Cleanup work in lndp_apply_perts.F90: define zs_ruc locally, remove trailing whitespaces, pass only one value lsoil from wrapper.

### CODE REVIEW

**Comment by DomHeinzeller** [comment]
@tanyasmirnova please merge this PR when you get the chance. Thanks!

**Review by tanyasmirnova — COMMENTED** [review]
Dom, we forgot about Noah-MP.  Everything that we do for the Noah LSM should work for Noah-MP because it has the same vertical structure in soil domain. Should we add NOah-MP option before merging?

**Comment by climbfuji** [comment]
> Dom, we forgot about Noah-MP. Everything that we do for the Noah LSM should work for Noah-MP because it has the same vertical structure in soil domain. Should we add NOah-MP option before merging?

I wouldn't, honestly. We are not testing it, and untested code is by definition broken.

**Comment by tanyasmirnova** [comment]
ok, sounds good. Then I'll merge the code.

**Pull request merged**
